; Minimal Surge base (no [Proxy Group], keep valid [Rule])
[General]
loglevel = notify
dns-server = system, 8.8.8.8, 114.114.114.114
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 17.0.0.0/8, localhost, *.local, *.crashlytics.com
external-controller-access = MixChina@0.0.0.0:8233
allow-wifi-access = true
enhanced-mode-by-rule = false
exclude-simple-hostnames = true
ipv6 = true
replica = false
internet-test-url = http://baidu.com
proxy-test-url = http://google.com
test-timeout = 3

[Proxy]
; Proxies will be inserted below by subconverter

[Rule]
FINAL,DIRECT
